# config/cucumber.yml
##YAML Template
---
default: --require features --tags ~@todo --tags ~@bug --tag ~@stress --tag ~@elevation_compiled
elevation: --require features --tags ~@todo --tags ~@bug --tags ~@stress
verify: --require features --tags ~@todo --tags ~@bug --tags ~@stress --tag ~@elevation_compiled -f progress
verify-elevation: --require features --tags ~@todo --tags ~@bug --tags ~@stress -f progress
jenkins: --require features --tags ~@todo --tags ~@bug --tags ~@stress --tags ~@options --tag ~@elevation_compiled -f progress
bugs: --require features --tags @bug
todo: --require features --tags @todo
all: --require features
